/**
 * Static catalogue mode — used when the site is hosted on a static host (e.g. GitHub Pages)
 * without the Express backend. Read-only catalogue data is loaded from static-data/catalog.json
 * (generated by `npm --prefix server run export:static`). Ordering, payments, accounts and the
 * Owner Portal require the real server and return a clear message instead.
 */
import type { Product } from '@/types';

export const STATIC_MODE = import.meta.env.VITE_STATIC_DATA === 'true';

interface Catalog {
  settings: any; rates: any; home: any; products: Product[]; facets: any; collections: any[]; collectionDetails: any[];
}
let catalog: Promise<Catalog> | null = null;
function load(): Promise<Catalog> {
  if (!catalog) {
    catalog = fetch(`${import.meta.env.BASE_URL}static-data/catalog.json`, { cache: 'no-cache' }).then((r) => {
      if (!r.ok) throw new Error('Catalogue data could not be loaded.');
      return r.json();
    });
    catalog.catch(() => { catalog = null; });
  }
  return catalog;
}

export class StaticModeError extends Error {
  status = 503;
}

const SYNONYMS: Record<string, string> = {
  ring: 'rings', necklace: 'necklaces', earring: 'earrings', jhumka: 'earrings', bangle: 'bangles',
  bracelet: 'bracelets', chain: 'chains', kada: 'bangles', haram: 'necklaces', stud: 'earrings',
};
const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function listProducts(all: Product[], qs: URLSearchParams) {
  let items = all.filter((p) => p.isActive !== false);
  const q = (qs.get('q') || '').toLowerCase().trim();
  if (q) {
    for (const t of q.split(/\s+/).slice(0, 6)) {
      const syn = SYNONYMS[t] || SYNONYMS[t.replace(/s$/, '')] || t;
      const re = new RegExp(`\\b${esc(t)}`, 'i');
      items = items.filter((p) => [p.name, p.description, p.sku, p.category, p.metalType, p.purity].some((f) => re.test(f || '')) || p.category === syn);
    }
  }
  const cat = qs.get('category');
  if (cat) items = items.filter((p) => p.category === cat || (['gold', 'silver', 'diamond'].includes(cat) && p.metalType === cat));
  const metal = qs.get('metal');
  if (metal) items = items.filter((p) => p.metalType === metal);
  const purity = qs.get('purity');
  if (purity) items = items.filter((p) => p.purity === purity);
  const min = qs.get('minPrice'); if (min) items = items.filter((p) => p.price >= Number(min));
  const max = qs.get('maxPrice'); if (max) items = items.filter((p) => p.price <= Number(max));
  const av = qs.get('availability'); if (av) items = items.filter((p) => p.availability === av);
  if (qs.get('featured') === 'true') items = items.filter((p) => p.isFeatured);
  const sort = qs.get('sort');
  items = [...items].sort((a, b) =>
    sort === 'price_asc' ? a.price - b.price : sort === 'price_desc' ? b.price - a.price : sort === 'name' ? a.name.localeCompare(b.name) : +new Date(b.createdAt) - +new Date(a.createdAt) || b.id - a.id
  );
  return items;
}

function quote(c: Catalog, lines: { productId: number; quantity: number }[]) {
  if (!lines?.length) throw new StaticModeError('Your cart is empty.');
  const merged = new Map<number, number>();
  lines.forEach((l) => merged.set(l.productId, (merged.get(l.productId) || 0) + l.quantity));
  const items = [...merged].map(([id, quantity]) => {
    const p = c.products.find((x) => x.id === id);
    if (!p) throw new StaticModeError('One of the products in your cart is no longer available.');
    if (p.availability === 'out_of_stock') throw new StaticModeError(`"${p.name}" is currently unavailable.`);
    const unitPaise = Math.round(p.price * 100);
    return { p, quantity, unitPaise, linePaise: unitPaise * quantity };
  });
  const s = c.settings.commerce;
  const sub = items.reduce((a, i) => a + i.linePaise, 0);
  const del = s.delivery.freeAbove > 0 && sub >= s.delivery.freeAbove * 100 ? 0 : Math.round(s.delivery.flatCharge * 100);
  let tax = 0;
  if (s.tax.mode === 'exclusive') tax = Math.round((sub * s.tax.ratePercent) / 100);
  if (s.tax.mode === 'inclusive') tax = Math.round(sub - sub / (1 + s.tax.ratePercent / 100));
  const total = sub + del + (s.tax.mode === 'exclusive' ? tax : 0);
  return {
    currency: s.currency,
    items: items.map((i) => ({
      productId: i.p.id, slug: i.p.slug, name: i.p.name, sku: i.p.sku, purity: i.p.purity, weightGrams: i.p.weightGrams,
      availability: i.p.availability, stock: i.p.stock, thumbUrl: i.p.images[0]?.thumbUrl ?? null,
      unitPrice: i.unitPaise / 100, quantity: i.quantity, lineTotal: i.linePaise / 100,
    })),
    subtotal: sub / 100, delivery: del / 100, freeDeliveryAbove: s.delivery.freeAbove,
    tax: { mode: s.tax.mode, ratePercent: s.tax.ratePercent, label: s.tax.label, amount: tax / 100 },
    total: total / 100,
  };
}

export async function staticApi(path: string, method: string, body: any): Promise<any> {
  const [p, query = ''] = path.split('?');
  const qs = new URLSearchParams(query);
  const phone = '9030957387';

  if (p.startsWith('/api/owner')) throw new StaticModeError('The Owner Portal needs the MPR JEWELLERY server, which is not connected to this website yet.');
  if (p === '/api/orders' && method === 'POST') throw new StaticModeError(`Online ordering is not available on this website yet. Please call or WhatsApp ${phone} to place your order.`);
  if (p.startsWith('/api/orders') || p.startsWith('/api/customers') || p === '/api/messages') {
    throw new StaticModeError(`This feature needs the MPR JEWELLERY server, which is not connected yet. Please call or WhatsApp ${phone}.`);
  }

  const c = await load();
  if (p === '/api/cart/quote') return quote(c, body?.items);
  if (method !== 'GET') throw new StaticModeError('This action is not available on this website yet.');
  if (p === '/api/settings') return c.settings;
  if (p === '/api/rates') return c.rates;
  if (p === '/api/home') return c.home;
  if (p === '/api/collections') return c.collections;
  if (p.startsWith('/api/collections/')) {
    const slug = decodeURIComponent(p.slice('/api/collections/'.length));
    const col = c.collectionDetails.find((x) => x.slug === slug);
    if (!col) throw Object.assign(new StaticModeError('This collection could not be found.'), { status: 404 });
    return col;
  }
  if (p === '/api/products') {
    const items = listProducts(c.products, qs);
    return { items, total: items.length, facets: c.facets };
  }
  if (p.startsWith('/api/products/')) {
    const slug = decodeURIComponent(p.slice('/api/products/'.length));
    const prod = c.products.find((x) => x.slug === slug);
    if (!prod) throw Object.assign(new StaticModeError('This product could not be found.'), { status: 404 });
    return prod;
  }
  throw Object.assign(new StaticModeError('Not found.'), { status: 404 });
}
